### PR TITLE
Header Added

### PR DESCRIPTION
**Pull request by Abhishek142004**
Header.jsx Component added with Required Assets

### CODE REVIEW

**Comment by EggBucketInterns** [comment]
@Abhishek142004  there is issue in responsiveness of header at around 1030px can you fix that and try to keep address option for as much as possible viewport like i think you can keep it till around 450px or even less till 350px

**Comment by Abhishek142004** [comment]
> @Abhishek142004 there is issue in responsiveness of header at around 1030px can you fix that and try to keep address option for as much as possible viewport like i think you can keep it till around 450px or even less till 350px image

I have done the required Changes 
as i am using sm, md, lg screen sizes so i have made it for all the available devices not for specific resolution 
so please check it only for devices 
and let me know if any change required

**Comment by EggBucketInterns** [comment]
> > @Abhishek142004 there is issue in responsiveness of header at around 1030px can you fix that and try to keep address option for as much as possible viewport like i think you can keep it till around 450px or even less till 350px image
> 
> I have done the required Changes as i am using sm, md, lg screen sizes so i have made it for all the available devices not for specific resolution so please check it only for devices and let me know if any change required


responsiveness looks great but i think you can fit  the address field below 814px
image

**Comment by Abhishek142004** [comment]
> > > @Abhishek142004 there is issue in responsiveness of header at around 1030px can you fix that and try to keep address option for as much as possible viewport like i think you can keep it till around 450px or even less till 350px image
> > 
> > 
> > I have done the required Changes as i am using sm, md, lg screen sizes so i have made it for all the available devices not for specific resolution so please check it only for devices and let me know if any change required
> 
> responsiveness looks great but i think you can fit the address field below 814px image

I have Added the Address icon in Mobile view 
if there is any issue let me know

**Review by EggBucketInterns — COMMENTED** [review]
bro don't modify App.jsx.
your changes are good and working .
But dont delete app.jsx file i think during testing u modified to test this so please remove modification of app.jsx

**Pull request merged**
